### ISSUE TITLE
Error isn't propegated to error handler.

### ISSUE THREAD

**Issue by Athas1980** [darylteo/rxjava-promises#12]
In a promise chain with the following 

    Promise<String> p = new Promise<>();
    p.then(methodWhichThrowsError())
    .then(somethingElse(), errorHandler());

The errorHandler is never invoked.

Trying to get a proper test case.

**Note** exceptions work fine. Errors such as `java.lang.AssertionError` cause the problem.

In fact its worse than that as the error doesn't seem to be handled or thrown anywhere its just caught then the promise is rejected but no output is shown.

Test Case can be found at https://github.com/Athas1980/rxjava-promises/blob/throwable-support/rxjava-promises/rxjava-promises-java/src/test/java/com/darylteo/rx/promises/test/ErrorTest.java

**Comment by Athas1980** [comment]
Testing this.

* **Solution 1**
This can be fixed changing the signature on com.darylteo.rx.promises.java.Promise to allow throwable everywhere. 
  * Cons this means changing all callers
* **Solution 2**
  Create a new Promise implementation in a new package. (Optionally deprecate origional)
  * Could be confusing to new implementors.

Other possible route involves not catching throwable, I haven't tested this.

* **Solution 3**
  Catch only exception when wrapping the method but then wrap errors in an ErrorException class.
  * Doesn't change the api.
  * Would need to be documented.

Let me know what the preferred solution would be and I can create a pull request.

**Comment by darylteo** [comment]
Morning, just woke up.

I just had a look at the RxJava source, and they do use the following:

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/exceptions/OnErrorFailedException.java
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/exceptions/OnErrorThrowable.java

I'm wondering if we can leverage them in some way. Let me have a look at my source again.

**Comment by darylteo** [comment]
Okay I have observed the issue and can reproduce.

**Comment by darylteo** [comment]
@Athas1980  can you review this and see if this works for you.

I have pushed 1.2.1-SNAPSHOT up to sonatype.

https://github.com/darylteo/rxjava-promises/compare/dev

**Comment by Athas1980** [comment]
Just pulled your dev branch and It does what I specifically wanted. I can handle Assertions from junit

I.e. my tests can fail correctly. :)

**Altered verion of your test**
	  @Test //(expected=AssertionError.class)
	  public void testError() throws Throwable {
	    final Promise<String> p = new Promise();
	    final CountDownLatch latch = new CountDownLatch(1);
	    final Result<Exception> result = new Result<Exception>();
	
	    p.then(new PromiseAction<String>() {
	      @Override
	      public void call(String s) {
	    	  //throw new AssertionError("hello world");
	        assertEquals(s, "This shouldn't match");
	      }
	    }).fail(new PromiseAction<Exception>() {
	      @Override
	      public void call(Exception e) {
	        result.value = e;
	        latch.countDown();
	      }
	    });
	
	    p.fulfill("Go");
	    latch.await(1, TimeUnit.SECONDS);
	    assertNotNull(result.value);
	    assertEquals(result.value.getClass(), OnErrorThrowable.class);
	    //assertEquals(result.value.getCause().getClass(), AssertionError.class);
	    throw result.value.getCause();
	  }

**Comment by darylteo** [comment]
Great. 1.2.1 pushed to sonatype. Should pop up on maven eventually.

**Comment by Athas1980** [comment]
You didn't happen to push the vertx-promises?

I don't see the 1.2.1 version of vertx promises. The java one yes.

Regards,

Wesley Acheson

**Comment by darylteo** [comment]
I wasn't aware you were using the vertx one...


I haven't done any vertx work recently and as such my interest in
maintaining it is minimal at best.

I will do a full push again (because I fail) but I haven't written any
tests for the vertx version.

Daryl

**Comment by Athas1980** [comment]
Why not just separate out the vertx mod?  I can see that It's not really doing too much different except implementing Handler. If you leave your library just doing the core successfully then the vertx mod could be maintained separately.

This also allow us to add in some util methods which I think would be useful for vertx.  (I'd have liked to add in a forAsync method) that unwraps AsyncResult.

Also it appears that the core hasn't been updated either see new issue.

**Comment by darylteo** [comment]
> Why not just separate out the vertx mod?

You are more than welcome to if you wish to do so! Personally I prefer using plain rxjava now that it has better lambda support.

>  the core hasn't been updated either see new issue.

My bad. I did naughty things.

**Comment by Athas1980** [comment]
Thanks so much Daryl.

> Personally I prefer using plain rxjava now that it has better lambda support.
 I actually haven't looked at rx at all really.
