### ISSUE TITLE
Promises Core not found

### ISSUE THREAD

**Issue by Athas1980** [darylteo/rxjava-promises#14]
Trying to use the maven central vertx-promises-java version 1.2.1

Doesn't exist. 

If I try to use the rxjava-promises-java version 1.2.1 it fails as it can't find rxjava-promises-core:1.2.1

**Comment by darylteo** [comment]
I apologise for my lack of discipline. Please try again in a few hours.

**Comment by darylteo** [comment]
https://oss.sonatype.org/content/repositories/releases/com/darylteo/vertx/vertx-promises-java/1.2.1/
